import * as vscode from 'vscode';
import { SidebarChatMessenger } from './sidebar-chat-messenger';

/**
 * Fix suggestion generated by the Looping Agent
 */
export interface FixSuggestion {
    type: 'correction' | 'generation';
    range: vscode.Range;
    diagnostic: vscode.Diagnostic;
    originalCode?: string;
    suggestedCode: string;
    explanation: string;
    confidence: number;
}

/**
 * Looping Agent
 * 
 * Continuously scans for issues, analyzes them, and determines appropriate fixes.
 * Can either correct existing code or generate new code where needed.
 */
export class LoopingAgent {
    private isActive: boolean = true;
    private analysisCount: number = 0;
    private fixesGenerated: number = 0;

    constructor(
        private agentId: string,
        private filePath: string,
        private messenger: SidebarChatMessenger
    ) {}

    /**
     * Analyze diagnostics and generate fix suggestions
     */
    public async analyzeDiagnostics(diagnostics: vscode.Diagnostic[]): Promise<FixSuggestion[]> {
        if (!this.isActive) {
            return [];
        }

        this.analysisCount++;
        const fixes: FixSuggestion[] = [];

        await this.messenger.sendMessage(
            `🔍 **Agent ${this.agentId}**: Analyzing ${diagnostics.length} error(s)...`,
            'info'
        );

        for (const diagnostic of diagnostics) {
            try {
                const fix = await this.generateFix(diagnostic);
                if (fix) {
                    fixes.push(fix);
                    this.fixesGenerated++;
                }
            } catch (error) {
                await this.messenger.sendMessage(
                    `❌ **Agent ${this.agentId}**: Failed to generate fix: ${error}`,
                    'error'
                );
            }
        }

        if (fixes.length > 0) {
            await this.messenger.sendMessage(
                `✨ **Agent ${this.agentId}**: Generated ${fixes.length} fix suggestion(s)`,
                'success'
            );
        }

        return fixes;
    }

    /**
     * Generate a fix for a specific diagnostic
     */
    private async generateFix(diagnostic: vscode.Diagnostic): Promise<FixSuggestion | null> {
        const document = await vscode.workspace.openTextDocument(this.filePath);
        const range = diagnostic.range;
        const originalCode = document.getText(range);

        // Analyze the error type and context
        const errorContext = this.analyzeErrorContext(diagnostic, document);
        
        // Determine if we need to correct existing code or generate new code
        const fixType = this.determinefixType(diagnostic, originalCode, errorContext);

        let suggestedCode: string;
        let explanation: string;
        let confidence: number;

        if (fixType === 'generation') {
            // Generate new code
            const generated = await this.generateNewCode(diagnostic, errorContext, document);
            suggestedCode = generated.code;
            explanation = generated.explanation;
            confidence = generated.confidence;
        } else {
            // Correct existing code
            const corrected = await this.correctExistingCode(diagnostic, originalCode, errorContext, document);
            suggestedCode = corrected.code;
            explanation = corrected.explanation;
            confidence = corrected.confidence;
        }

        // Only return fixes with sufficient confidence
        if (confidence < 0.5) {
            await this.messenger.sendMessage(
                `⚠️ **Agent ${this.agentId}**: Low confidence fix skipped (${Math.round(confidence * 100)}%)`,
                'warning'
            );
            return null;
        }

        return {
            type: fixType,
            range,
            diagnostic,
            originalCode,
            suggestedCode,
            explanation,
            confidence
        };
    }

    /**
     * Analyze error context to better understand the issue
     */
    private analyzeErrorContext(diagnostic: vscode.Diagnostic, document: vscode.TextDocument): any {
        const line = diagnostic.range.start.line;
        const startLine = Math.max(0, line - 5);
        const endLine = Math.min(document.lineCount - 1, line + 5);
        
        const contextRange = new vscode.Range(startLine, 0, endLine, document.lineAt(endLine).text.length);
        const context = document.getText(contextRange);

        return {
            errorMessage: diagnostic.message,
            errorCode: diagnostic.code,
            severity: diagnostic.severity,
            source: diagnostic.source,
            surroundingCode: context,
            lineNumber: line,
            languageId: document.languageId,
            fileName: vscode.workspace.asRelativePath(document.uri)
        };
    }

    /**
     * Determine if we need to correct or generate code
     */
    private determinefixType(
        diagnostic: vscode.Diagnostic,
        originalCode: string,
        context: any
    ): 'correction' | 'generation' {
        // Check if there's actual code to correct
        if (!originalCode.trim()) {
            return 'generation';
        }

        // Common patterns that require generation
        const generationPatterns = [
            /missing function/i,
            /cannot find name/i,
            /module not found/i,
            /property.*does not exist/i,
            /is not defined/i,
            /undeclared identifier/i
        ];

        for (const pattern of generationPatterns) {
            if (pattern.test(diagnostic.message)) {
                return 'generation';
            }
        }

        // Default to correction
        return 'correction';
    }

    /**
     * Correct existing code
     */
    private async correctExistingCode(
        diagnostic: vscode.Diagnostic,
        originalCode: string,
        context: any,
        document: vscode.TextDocument
    ): Promise<{ code: string; explanation: string; confidence: number }> {
        const errorMessage = diagnostic.message.toLowerCase();
        let suggestedCode = originalCode;
        let explanation = '';
        let confidence = 0.8;

        // TypeScript/JavaScript specific fixes
        if (context.languageId === 'typescript' || context.languageId === 'javascript') {
            // Missing semicolon
            if (errorMessage.includes('semicolon')) {
                suggestedCode = originalCode.trimEnd() + ';';
                explanation = 'Added missing semicolon';
                confidence = 0.95;
            }
            // Undefined variable - add declaration
            else if (errorMessage.includes('undefined') || errorMessage.includes('not declared')) {
                const varName = this.extractVariableName(originalCode);
                suggestedCode = `let ${varName};\n${originalCode}`;
                explanation = `Added variable declaration for '${varName}'`;
                confidence = 0.7;
            }
            // Type mismatch
            else if (errorMessage.includes('type') && errorMessage.includes('not assignable')) {
                suggestedCode = await this.fixTypeMismatch(originalCode, diagnostic, document);
                explanation = 'Fixed type mismatch';
                confidence = 0.75;
            }
            // Missing import
            else if (errorMessage.includes('cannot find module')) {
                const moduleName = this.extractModuleName(diagnostic.message);
                suggestedCode = `import ${moduleName} from '${moduleName}';\n${originalCode}`;
                explanation = `Added import statement for '${moduleName}'`;
                confidence = 0.8;
            }
        }

        // Python specific fixes
        else if (context.languageId === 'python') {
            // Indentation error
            if (errorMessage.includes('indent')) {
                suggestedCode = this.fixIndentation(originalCode, document, diagnostic.range.start.line);
                explanation = 'Fixed indentation';
                confidence = 0.9;
            }
            // Missing colon
            else if (errorMessage.includes('colon')) {
                suggestedCode = originalCode.trimEnd() + ':';
                explanation = 'Added missing colon';
                confidence = 0.95;
            }
            // Undefined name
            else if (errorMessage.includes('is not defined')) {
                const varName = this.extractVariableName(originalCode);
                suggestedCode = `${varName} = None  # TODO: Define this variable\n${originalCode}`;
                explanation = `Added placeholder for undefined variable '${varName}'`;
                confidence = 0.6;
            }
        }

        // Generic fixes for other languages
        else {
            // Syntax error - try basic cleanup
            suggestedCode = originalCode.trim();
            explanation = 'Applied basic syntax cleanup';
            confidence = 0.5;
        }

        return { code: suggestedCode, explanation, confidence };
    }

    /**
     * Generate new code to fix the issue
     */
    private async generateNewCode(
        diagnostic: vscode.Diagnostic,
        context: any,
        document: vscode.TextDocument
    ): Promise<{ code: string; explanation: string; confidence: number }> {
        let generatedCode = '';
        let explanation = '';
        let confidence = 0.7;

        const errorMessage = diagnostic.message.toLowerCase();

        // Generate missing function
        if (errorMessage.includes('cannot find name') || errorMessage.includes('is not defined')) {
            const functionName = this.extractFunctionName(diagnostic.message);
            
            if (context.languageId === 'typescript' || context.languageId === 'javascript') {
                generatedCode = `function ${functionName}() {\n    // TODO: Implement this function\n    throw new Error('Not implemented');\n}`;
                explanation = `Generated stub for missing function '${functionName}'`;
            } else if (context.languageId === 'python') {
                generatedCode = `def ${functionName}():\n    """TODO: Implement this function"""\n    raise NotImplementedError()`;
                explanation = `Generated stub for missing function '${functionName}'`;
            }
            confidence = 0.75;
        }
        
        // Generate missing class
        else if (errorMessage.includes('cannot find class') || errorMessage.includes('class') && errorMessage.includes('not found')) {
            const className = this.extractClassName(diagnostic.message);
            
            if (context.languageId === 'typescript' || context.languageId === 'javascript') {
                generatedCode = `class ${className} {\n    constructor() {\n        // TODO: Implement constructor\n    }\n}`;
                explanation = `Generated stub for missing class '${className}'`;
            } else if (context.languageId === 'python') {
                generatedCode = `class ${className}:\n    """TODO: Implement this class"""\n    pass`;
                explanation = `Generated stub for missing class '${className}'`;
            }
            confidence = 0.7;
        }

        // Generate missing import/module
        else if (errorMessage.includes('module') && (errorMessage.includes('not found') || errorMessage.includes('cannot find'))) {
            const moduleName = this.extractModuleName(diagnostic.message);
            
            if (context.languageId === 'typescript' || context.languageId === 'javascript') {
                generatedCode = `import ${moduleName} from '${moduleName}';`;
                explanation = `Generated import for module '${moduleName}'`;
            } else if (context.languageId === 'python') {
                generatedCode = `import ${moduleName}`;
                explanation = `Generated import for module '${moduleName}'`;
            }
            confidence = 0.8;
        }

        return { code: generatedCode, explanation, confidence };
    }

    /**
     * Helper: Extract variable name from code or error message
     */
    private extractVariableName(text: string): string {
        const match = text.match(/\b([a-zA-Z_$][a-zA-Z0-9_$]*)\b/);
        return match ? match[1] : 'variable';
    }

    /**
     * Helper: Extract function name from error message
     */
    private extractFunctionName(message: string): string {
        const match = message.match(/['"`]([a-zA-Z_$][a-zA-Z0-9_$]*)['"`]/);
        return match ? match[1] : 'unknownFunction';
    }

    /**
     * Helper: Extract class name from error message
     */
    private extractClassName(message: string): string {
        const match = message.match(/['"`]([A-Z][a-zA-Z0-9_$]*)['"`]/);
        return match ? match[1] : 'UnknownClass';
    }

    /**
     * Helper: Extract module name from error message
     */
    private extractModuleName(message: string): string {
        const match = message.match(/['"`]([a-zA-Z0-9_\-\.\/]+)['"`]/);
        return match ? match[1] : 'unknown';
    }

    /**
     * Helper: Fix type mismatch
     */
    private async fixTypeMismatch(code: string, diagnostic: vscode.Diagnostic, document: vscode.TextDocument): Promise<string> {
        // Try to add type casting or conversion
        return code + ' as any'; // Simple fallback
    }

    /**
     * Helper: Fix indentation
     */
    private fixIndentation(code: string, document: vscode.TextDocument, lineNumber: number): string {
        // Get expected indentation from previous line
        if (lineNumber > 0) {
            const prevLine = document.lineAt(lineNumber - 1).text;
            const prevIndent = prevLine.match(/^\s*/)?.[0] || '';
            
            // If previous line ends with colon, increase indentation
            if (prevLine.trimEnd().endsWith(':')) {
                return '    ' + prevIndent + code.trimStart();
            }
            
            return prevIndent + code.trimStart();
        }
        return code;
    }

    /**
     * Get agent statistics
     */
    public getStats(): { analysisCount: number; fixesGenerated: number } {
        return {
            analysisCount: this.analysisCount,
            fixesGenerated: this.fixesGenerated
        };
    }

    /**
     * Stop the agent
     */
    public stop(): void {
        this.isActive = false;
    }

    /**
     * Check if agent is active
     */
    public isAgentActive(): boolean {
        return this.isActive;
    }
}
